### ISSUE TITLE
Unify decision variable and problem size info handling

### ISSUE THREAD

**Issue by yunlongxu-numagic** [numagic/lumos#10]
This is probably the largest weakness in the backbone, and is messy. 

### Unify problem size info
there are various places that one could get the size of the problem:
```python
# from ocp.model
ocp.model.num_states
# ocp directly
ocp.num_dec
# and from ocp.dec_var_operator
ocp.dec_var_operator.num_dec
```
- [ ] unify problem size info construction and retrieval #12 

### Unify stagevar and global var handling syntax
Stage and Global Variable handling very different, so requiring `if/else` a lot
- for getting decision variable indices
- for `BoundConfig` and `ScaleConfig`
- [x] unify stagevar and global var handling #11 

### cleanup indexing methods
It makes sense to have unified methods for indexing the decision variables, eg "get me that decision variable (at a specific stage or not) from the decision variable array"
- mostly in `DecVarOperator`
- also some similar methods in `Model`
- [x] clean up indexing methods #11 

### `DecVarOperator` uses a lot of jnp operations, can we replace them with normal np or lnp?
- [x] clean up jnp ops in `DecVarOperator` #11

**Comment by yunlongxu-numagic** [comment]
#Unify Sizing info

### Methods in `Model`
```python3
    @property
    def num_inputs(self):
        return self.get_num_vars(group="inputs")

    @property
    def num_outputs(self):
        return self.get_num_vars(group="outputs")

    @property
    def num_residuals(self):
        return self.get_num_vars(group="residuals")

    @property
    def num_con_outputs(self):
        return self.get_num_vars(group="con_outputs")

    @property
    def num_implicit_res(self):
        return self.num_states + self.num_con_outputs + self.num_residuals

    @property
    def num_implicit_var(self):
        return sum([self.get_num_vars(g) for g in self._implicit_inputs])

    @property
    def num_states(self):
        return self.get_num_vars(group="states")
```

### Methods in `DecVarOperator`
```python3
    @property
    def num_var_stage(self):
        return sum(self.get_stage_var_size(g) for g in self._stage_var_groups)

    @property
    def num_var_interval(self):
        return self.num_var_stage * self.num_stages_per_interval

    @property
    def num_stages(self):
        return self.num_intervals * (self.num_stages_per_interval - 1) + 1

    @property
    def num_all_stage_var(self):
        return self.num_stages * self.num_var_stage

    @property
    def num_global_var(self):
        return len(self._global_var_names)

    @property
    def num_dec(self):
        return self.num_all_stage_var + self.num_global_var
```

### Methods in `OCP`
Most are piping directly attributes from either `DecVarOperator` or `Model`
```python3
    @property
    def num_stages(self):
        return self.dec_var_operator.num_stages

    @property
    def num_var_stage(self):
        return self.dec_var_operator.num_var_stage

    @property
    def num_var_interval(self):
        return self.dec_var_operator.num_var_interval

    @property
    def num_dec(self):
        return self.dec_var_operator.num_dec

    @property
    def num_con_stage(self):
        return self.model.num_implicit_res

    @property
    def num_con_interval(self):
        return self.model.num_states * self.transcription.num_constraints_per_interval

    @property
    def num_total_con_interval(self):
        return self.num_con_interval * self.num_intervals

    @property
    def num_total_con_stage(self):
        return self.num_con_stage * self.num_stages
```

**Comment by yunlongxu-numagic** [comment]
Closing this issue for now; relatively happy with the unification of indexing methods; mildly acceptable for the unifying size info part, but don't have better ideas now and have other higher priority items to work on
